- hosts: masters, nodes
  sudo: yes
  tasks: 
    - name: Update repositories cache and install DockerCE
      apt:
        name: docker.io
        update_cache: yes
    - name: Add an Apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
    - name: Update repositories cache and install Kubernetes
      apt:
        name: kubeadm
        update_cache: yes