- hosts: masters, nodes
  tasks:
  - name: Set authorized key taken from file
    authorized_key:
      user: acp
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"